#Copy snapshot from existing snapshot with encryption
---
- hosts: localhost
  tasks:
  - name: get snap id
    ec2_ami_facts:
      filters:
        "tag:Name": "Golden"
      region: us-east-1
    register: amiinfo
  - name: create a snapshot form another snapshot
    ec2_snapshot_copy:
      source_region: us-east-1
      region: us-east-1
      source_snapshot_id: "{{amiinfo.images[0].block_device_mappings[0].ebs.snapshot_id}}"
      encrypted: yes
      wait: yes
      tags:
        Name: Golden_snap
    register: snap_id
